[build]
  publish = "out"
  command = "cp netlify.prod.toml netlify.toml && cp .env.production .env.local && cp firebase.prod.json firebase.json && npm run export"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/blog/*"
  to = "https://cms.applanding.page/blog/:splat"
  status = 200

[[redirects]]
  from = "/sitemap-blog.xml"
  to = "https://cms.applanding.page/sitemap.xml"
  status = 200

[[redirects]]
  from = "/showcase/*"
  to = "https://showcase.applanding.page/showcase/:splat"
  status = 200

[[redirects]]
  from = "/sitemap-showcase.xml"
  to = "https://showcase.applanding.page/sitemap.xml"
  status = 200

[[redirects]]
  from = "/:slug"
  to = "https://firebasestorage.googleapis.com/v0/b/apphome-page.appspot.com/o/public%2F:slug%2Findex.html?alt=media"
  status = 200
[[redirects]]
  from = "/:slug/bin/:file"
  to = "https://firebasestorage.googleapis.com/v0/b/apphome-page.appspot.com/o/public%2F:slug%2Fbin%2F:file?alt=media"
  status = 200

[[redirects]]
  from = "/_bin/:slug"
  to = "https://firebasestorage.googleapis.com/v0/b/apphome-page.appspot.com/o/public%2F_bin%2F:slug?alt=media"
  status = 200
[[redirects]]
  from = "/_bin/:type/:slug"
  to = "https://firebasestorage.googleapis.com/v0/b/apphome-page.appspot.com/o/public%2F_bin%2F:type%2F:slug?alt=media"
  status = 200
